# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
Dotenv.load

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    increment_version_code(gradle_file_path: "./app/build.gradle")
    gradle(task: "clean assembleRelease")

    last_commits = `git log -5 --pretty=format:"%h - %s"`.strip

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "testers",
      service_credentials_file: "./fastlane/getmobil-case-study-service-acount.json",
      release_notes: last_commits
      #android_artifact_type: 'AAB',
      #android_artifact_path: "./app/build/outputs/bundle/release/app-release.aab"
    )
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
